version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      composer-patch-and-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    labels:
      - quality
      - dependencies

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      npm-patch-and-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    labels:
      - quality
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]
    labels:
      - quality
      - infrastructure

  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      compose-images:
        patterns: ["*"]
    labels:
      - infrastructure
