<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504182123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create deals table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE deal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                title VARCHAR(255) NOT NULL,
                close_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                currency VARCHAR(3) NOT NULL,
                expected_value_cents INT NOT NULL,
                lost_reason VARCHAR(255) DEFAULT NULL,
                notes TEXT DEFAULT NULL,
                probability INT DEFAULT NULL,
                stage VARCHAR(255) NOT NULL,
                lead_id INT NOT NULL,
                project_id INT DEFAULT NULL,
                owner_id INT DEFAULT NULL, PRIMARY KEY (id),
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
            )
        ');
        $this->addSql('CREATE INDEX IDX_E3FEC11655458D ON deal (lead_id)');
        $this->addSql('CREATE INDEX IDX_E3FEC116166D1F9C ON deal (project_id)');
        $this->addSql('CREATE INDEX IDX_E3FEC1167E3C61F9 ON deal (owner_id)');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC11655458D FOREIGN KEY (lead_id) REFERENCES lead (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC116166D1F9C FOREIGN KEY (project_id) REFERENCES client_projects (id)');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC1167E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC11655458D');
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC116166D1F9C');
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC1167E3C61F9');
        $this->addSql('DROP TABLE deal');
    }
}
