<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260503171901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the client projects table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
        'CREATE TABLE client_projects (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('CREATE UNIQUE INDEX UNIQ_72758361989D9B62 ON client_projects (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE client_projects');
    }
}
