<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504175256 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the leads table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE lead (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL,
                company VARCHAR(255) DEFAULT NULL,
                phone VARCHAR(255) DEFAULT NULL,
                street VARCHAR(255) DEFAULT NULL,
                zip_code VARCHAR(255) DEFAULT NULL,
                city VARCHAR(255) DEFAULT NULL,
                state VARCHAR(255) DEFAULT NULL,
                country VARCHAR(255) DEFAULT NULL,
                source VARCHAR(255) NOT NULL,
                owner_id INT DEFAULT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('CREATE INDEX IDX_289161CB7E3C61F9 ON lead (owner_id)');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE "user" ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER updated_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB7E3C61F9');
        $this->addSql('DROP TABLE lead');
        $this->addSql('ALTER TABLE "user" ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE "user" ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
    }
}
